### ISSUE TITLE
Jacob learns Stencil

### ISSUE THREAD

**Issue by jheftmann** [micdijkstra/Stencil#12]
- [x] is there an equivalent for [.img-responsive](http://getbootstrap.com/css/#images):
```
%img-responsive {
  max-width: 100%;
  height: auto;
}
```

or should this be the default behavior? I noticed I had to drop it in on images.

- [x] possible to do have a compiler for Stencil-CSS projects?

**Comment by micdijkstra** [comment]
@jheftmann I've documented the modifiers here, and specifically the responsive image one: https://github.com/micdijkstra/Stencil#responsive

Also, I've added it to the default `global/_base.scss` file so we get it out of the box, but you know it's configurable.

**Comment by jheftmann** [comment]
super useful. nice.

(how you feeling about having a little extra time on your hands? good or bad?)

**Comment by jheftmann** [comment]
a quick little grid section would be nice, maybe?
