### ISSUE TITLE
Email tools

### ISSUE THREAD

**Issue by jheftmann** [micdijkstra/stencil#26]
+ [ ] inliner removes closing `;` from last inline style
+ [ ] remove whitespace when inlining
+ [ ] prevent inliner from adding unused styles to `<style>`
+ [ ] some styles for responsive layout tools not being inlined
+ [ ] styles are adding `font-family` to `td` (and maybe other elements) where it's not necessary

**Comment by micdijkstra** [comment]
Moved to: https://github.com/micdijkstra/stencil-ruby/issues/2
